### PR TITLE
Confirm key existence strictly

### PR DESCRIPTION
**Pull request by hakatashi**
I've experienced problem when I combined [browserify](https://github.com/substack/node-browserify) and [gulp-mocha](https://www.npmjs.com/package/gulp-mocha) tasks in my Gulp task. I use [should.js](https://www.npmjs.com/package/should) for my mocha test cases and it breaks code with defiining Object.prototype.should.

Though I know extending native objects are bizarre, checking key existence without hasOwnProperty is enough bad. Please confirm my quick fix.

### CODE REVIEW

**Comment by defunctzombie** [comment]
Alternatively, I think a better fix would be to change this line to use `Object.create(null)` to avoid any prototype (and thus making it a hash map like object as we want).

https://github.com/hakatashi/node-browser-resolve/blob/patch-1/index.js#L80

See if that solves your problem and lets update the PR to do that instead since it better aligns with the intended use of the `shims` var.

**Comment by hakatashi** [comment]
It seems nice. I'll perform update soon.

**Comment by hakatashi** [comment]
@defunctzombie I've done editing PR. To clearify problem I also added a test case which might previously failed.

**Comment by defunctzombie** [comment]
Awesome. Please remove the first two commits since they are no longer needed.

**Comment by hakatashi** [comment]
done

**Pull request merged**
