### PR TITLE
Fixing resolution of deep module references without a file extension

### PR DESCRIPTION
**Pull request by src-code**
Addresses issue #69.  Original code had a bug in it where it'd append a second `.js` extension if the path already had an extension, rather than appending the extension if the path didn't already have an extension.  

I also went ahead and added handling for `.json` as well, since `require.resolve()` does the same.

### CODE REVIEW

**Comment by defunctzombie** [comment]
@src-code does the nodejs require function fallback to trying json files?

**Comment by defunctzombie** [comment]
referring to this line: https://github.com/defunctzombie/node-browser-resolve/pull/73/files#diff-168726dbe96b3ce427e7fedce31bb0bcR192

**Comment by src-code** [comment]
@defunctzombie Yeah, I believe so, based on this doc: https://nodejs.org/docs/latest-v0.12.x/api/modules.html#modules_all_together

**Comment by defunctzombie** [comment]
great!

**Comment by src-code** [comment]
Thank you! :+1:

**Pull request merged**
