### PR TITLE
Add LICENSE file with complete attribution text.

### PR DESCRIPTION
**Pull request by mkillianey**

### CODE REVIEW

**Comment by mkillianey** [comment]
How would you like to be attributed for licensing purposes?  I'm guessing that since you published under the MIT license, you wanted to use that template, but if this isn't how you want your attribution to appear, could you provide the full text that you'd like to be used?

**Comment by defunctzombie** [comment]
Can you leave the readme portion plz. The rest looks good.

**Comment by mkillianey** [comment]
Absolutely!

**Comment by mkillianey** [comment]
Thanks muchly, both for confirming the license and for making this available in the first place!

**Pull request merged**
